= Asylum Seekers and Refugees

== Preamble

Handling of asylum seekers is one of the great policy failures of recent years. Domestically, political and legal processes are mired in buck-passing and blame - a dysfunction mirrored in wider regional disputes.[#Aus faceoff][#Regional refugee protection][#Immigration detention in Aus] The backlog of boat arrivals has overwhelmed capacity for processing, drownings at sea continue to escalate, and growing evidence is emerging of inept and inhumane handling of the problem in Australia and overseas.[#RCA sub]

A crisis on such a scale requires a regional solution. We believe efforts should begin at once to set up a single regional asylum seeker 'queue'. Asylum seekers arriving anywhere in the region would be subject to a single processing system overseen by an independent body with all participating nations accepting a share of approved refugees. The existence of a common regional queue would remove specific incentives to travel to Australia, reducing drowning and deterring backdoor economic migration. A transparent allocation process should reduce disputes between nations, and pooling of information should improve document and identity checking. The creation of a new system of oversight allows for a best practice approach built from the ground up, with a humane appeals process and a means for swift and safe return of arrivals deemed not to be asylum seekers.

Such a scheme would require funding, leadership, and specific incentives provided by Australia to encourage sign-up. However, Australia currently spends over $1 billion per year on detention facilities,[#4 steps] and redirection of these funds will free up significant resources. Nations such as Indonesia would have strong incentives to sign up, both to receive aid, and to obtain help with settling their own large backlog of asylum seekers. As participating countries would be required to sign the UN Refugee Convention, funding and aid from Australia could become a mechanism for improving region-wide standards in asylum seeker handling.

Asylum seeking is lawful, and detention should not last longer than the minimum time-frame necessary to assess claims and conduct health and security checks. Approved asylum seekers can be brought into the community, provided with support and training, and settled in areas where jobs remain persistently vacant (the National Farmers Federation estimates around 96,000 jobs are unfilled in regional areas).[#Labour shortage]

The Pirate Party believes it is past time that our response to the plight of vulnerable people embodied our best qualities instead of our worst.

== Policy Text

=== Set up a single regional asylum seeker "queue" comprising willing refugee convention signatory countries ===

* Australia to offer funding and leadership.
* All countries take a share of asylum seekers according to a transparent allocation process.
* A single process will provide common housing, education, treatment and assessment for all asylum seekers who arrive in any participating country.
  * Assessments, health & security checks to be conducted in common, agreed places.
  * Process to be overseen by UNHCR or by an independent, expert organisation.
  * Assessment of backlogged claims to be fast-tracked.
  * Families should be kept together, and asylum seekers may submit preferences on a destination nation.
    * Preferences may be taken into account, but final decisions to be made by the overseeing body in line with agreed quotas.
  * Nations to pool information to assist with document and identity checking.
  * Processing will follow all relevant international law and treaties.

=== Refugees accepted into Australia to be released into the community ===

* Successful asylum seekers assigned to Australia to be brought safely as refugees (by plane or naval vessel).
* Conditions of release should include reporting requirements and continued availability for processing.
* Peer-driven community training and social services will help refugees understand their legal rights, build social networks, and overcome disadvantage (language barriers, skills, trauma, etc).
* Refugees to be provided with a basic income (see PPAU welfare policy), a right to work, and a pathway to citizenship.
* Savings from closing offshore detention centres to be redirected in order to provide:
  * Incentives for regional nations to sign the refugee convention and engage with the plan.
  * Resources to speed processing times, develop humane processing practices, and improve support services in destination countries.

== References

[#Aus faceoff]: "Australia, Indonesia to face off over people smuggling", UOI, June 26 2013, http://www.upi.com/Top_News/Special/2013/06/26/Australia-Indonesia-to-face-off-over-people-smuggling/UPI-84911372226940/ (Accessed June 27 2013)
[#Regional refugee protection]: Power, Refugee Council of Australia, "Regional Refugee Protection in the Asia Pacific", 28 June 2012, http://www.refugeecouncil.org.au/n/media/120628_Parlt_Bill.pdf
[#Immigration detention in Aus]: Parliamentary Library, "Immigration detention in Australia", 20 March 2013, http://www.aph.gov.au/About_Parliament/Parliamentary_Departments/Parliamentary_Library/pubs/BN/2012-2013/Detention#_Toc351535446
[#RCA sub]: Refugee Council of Australia, "Submissions to Joint Parlimentary Committee on Human Rights Examination of the Migration (Regional Processing) Package of Legislation", Sections 1.7, 1.8, 2.2, 2.3, April 2013, http://www.refugeecouncil.org.au/r/sub/1304-EP.pdf
[#4 steps]: Burnside, Julian, "Four steps to more humane refugee processing", 23 November 2012, http://theconversation.com/four-steps-to-more-humane-refugee-processing-10945 (Accessed June 27 2013)
[#Labour shortage]: Beeby, "Labour shortage costing farmers $150m a year", January 6, 2012, http://www.theage.com.au/victoria/labour-shortage-costing-farmers-150m-a-year-20120105-1pmvz.html (Accessed June 27 2013)