# Digital Liberties Policy Text

## Preamble ##

The grassroots nature of the Internet is causing considerable disruption to traditional power structures.[#Secret treaty][#Global effort to curb][#telecom data retention overview][#Internet Enemies] Unsurprisingly, this is leading to push-back: corporate and government entities have been trying for years to increase control over the Internet through a range of measures including censorship, reduction of access, treaties to reduce the rights of Internet users, and ever-broader surveillance and monitoring powers.[#No tolls]
Attempts to control the Internet take different forms over time, but all are justified through references to crime and other undesirable activities. They also all share one critical flaw: they are easily evaded by those with technical knowledge. They ultimately reduce the freedoms of the public while doing nothing to curb criminal behaviour. The Pirate Party will always defend the founding principles of the Internet, and resist any and all attempts to control it. A fast and free Internet, open to all, is a safeguard not just for our economy and culture, but for our basic rights.

### Net neutrality

Net neutrality is a fundamental principle behind the development of the Internet. It ensures that the Internet is free and open to all by preventing gatekeepers from blocking, speeding up, or slowing down content based on the source, destination or owner. Net Neutrality guarantees that even the smallest entrepreneurs have the same access standards as established firms.[#No tolls] The absence of such a guarantee would represent a perpetual threat to generations of new entrants.
Content providers and ISPs have undermined net neutrality by seeking to differentiate among different forms of information and data flow, and impose priorities. Abandoning Net Neutrality and subjecting Internet traffic to a commercial veto will hurt competition and innovation, and allow service providers to preference or block protocols and force consumers to use less desirable options.
Free, open and non-discriminatory access to the Internet is essential for our democracy and for our economic well-being and the Pirate Party will seek the adoption of clear net neutrality principles to protect the Internet from the introduction of any discriminatory practices.

### Data retention

Surveillance of the public is expanding constantly, and has reached a point which threatens essential trust between the state and the citizen.[#Web inventor says bad idea][#telecom data retention overview]
Plans have been tabled to expand surveillance further which would force ISPs to retain telephone and Internet data for 2 years, and force people to reveal their passwords on demand. This is a gross invasion of privacy and will create a vast database of material. Ultimately this database could become accessible through many channels not mentioned in the legislation, including subpoenas. The database will pose little threat to criminal activity, since many technical avenues currently exist through which data retention can be avoided.
While data retention is only a proposal at present, recent revelations show that Australians are already subject to an array of secret, warrantless spying on emails, chats, photographs, documents and website addresses.[#Prism][#intel mining data][#NSA slides explain] Such spying poses little threat to terrorists: terrorist forums are not indexed by most search engines and do not inhabit the servers targeted by the PRISM program.[#Jihadism] However, mass-trawling of personal data poses a significant threat to the liberties of the global public and undermines cooperation and trust between citizens and the state. Unrestricted surveillance of the public combined with total obscurity for the state is untenable. Far more legitimacy, trust, and effectiveness will be earned by applying proper oversight and inbuilt protections for civil liberties, including proper use of warrants.

### Censorship

Internet censorship proposals create a permanent infrastructure for web blocking, and connect it to a permanently shifting category of banned content. The RC classification has been altered frequently by parliament and has become patchwork and inconsistent.[#refused classification] We believe that the government should look to adequately funding law enforcement, removing illegal content and prosecuting those responsible for the manufacture of the material, rather than funding a filter that slows connection speeds, is liable to wrongly block websites and is easily circumvented.
Households may choose censorship programs for their own use, but that is the prerogative of parents: they must be permitted to make decisions for their own families, and the government should trust them to do so responsibly.
New censorship proposals come on top of existing, secret censorship mechanisms. Section 313 of the Telecommunications Act has been used by officials to block access to around 250,000 legitimate websites to date, with no application of oversight and accountability.[#notice 2821][#ASIC spiderweb][#Secret blocking] We believe the rampant misuse of this provision warrants its removal, with any replacement clause to be subject to proper consultation and higher legislative standards.

## Policy Text ##

### Provide universal access to a fast, neutral Internet ###

* Institute a common carriage agreement and legal protection for Net Neutrality, and ban the practice of screening, or prioritizing traffic based on packet sources or destinations, unless
  1. The default package offered to the user of an ISP contains no such screening or prioritising; and
  2. The user can opt-in to a package that will prioritise certain types of traffic by protocol or destination.
* Allow exceptions in the case of a court order.
* Allow generic prioritisation of traffic based on protocol types defined by the IETF.
* Support fibre-to-the-premises infrastructure projects to help build a vibrant digital society.

### Install explicit protections for privacy and digital rights ###

* Oppose mandatory censorship and web-blocking architecture.
  * Repeal the Broadcasting Services Amendment (Online Services) Act 1999.
  * Repeal the Communications Legislation Amendment (Content Services) Act 2007.
  * Delete section 313 of the Telecommunications Act.
  * Ensure no criminal offence applies for linking on the Internet.
* Prevent warrantless monitoring of internet use among the general public.
  * Oppose and repeal any legal mechanisms enacted to create records of Internet use among the general public.
    * Records obtained through such schemes to be securely deleted.
    * No authorisation for unnecessary data collection.
  * Replace the Cybercrime Act with more appropriate legislation for the digital age.
  * Conduct an independent review of the Telecommunications Interception and Access Act to ensure digital liberties are properly protected.
  * No future access to phone or internet metadata without a warrant.
  * Ban practice of agencies obtaining private information on Australian citizens through the NSA or other offshore surveillance not subject to Australian protections and laws.
  * Anti-terrorism practice to emphasise greater use of informants and targeted infiltration.
* Ensure individuals have a legally protected right to control data collection on devices they own.
  * Control should cover duration data is retained for, encryption and sending of data, and when data is deleted.
* Ensure no penalties apply to individuals who refuse to provide passwords or assist in decrypting information (in line with existing legal practices regarding self-incrimination).

## References ##

[#Secret treaty]: Geist, Michael. "Secret Treaty To Curb Internet Freedom." Global Research Centre for Research on Globalization. 13 April, 2010. http://www.globalresearch.ca/secret-treaty-to-curb-internet-freedom/18782 (Accessed 30 March 2013).
[#Global effort to curb]: Agence France-Presse. "U.S. diplomat warns of global effort to curb Internet freedom." The Raw Story. 7 March, 2013. http://www.rawstory.com/rs/2013/03/07/u-s-diplomat-warns-of-global-effort-to-curb-internet-freedom/ (Accessed 30 March 2013)
[#telecom data retention overview]: Brew, Nigel. "Telecommunications data retention—an overview." Foreign Affairs, Defence and Security Section. 24 October, 2012. http://www.aph.gov.au/About_Parliament/Parliamentary_Departments/Parliamentary_Library/pubs/BN/2012-2013/DataRetention (Accessed 30 March 2013).
[#Internet Enemies]: Reporters Without Borders. "Internet Enemies: Report 2012." March 2012. http://march12.rsf.org/i/Report_EnemiesoftheInternet_2012.pdf (Accessed 30 March 2013).
[#No tolls]: Lessig, Lawrence & McChesney, Robert W. "No Tolls on The Internet." The Washington Post. 8 June, 2006. http://www.washingtonpost.com/wp-dyn/content/article/2006/06/07/AR2006060702108.html (Accessed 30 March 2013).
[#Web inventor says bad idea]: McDonald, Stephanie. "Web inventor says proposed data retention laws a "bad idea"." Computerworld. 29 January, 2013. http://www.computerworld.com.au/article/452142/web_inventor_says_proposed_data_retention_laws_bad_idea_/ (Accessed 30 March 2013).
[#Prism]: Greenwald and MacAskill, "NSA Prism program taps in to user data of Apple, Google and others", June 7 2013, http://www.guardian.co.uk/world/2013/jun/06/us-tech-giants-nsa-data(Accessed June 20 2013)
[#intel mining data]: Gellman and Poitras, "U.S., British intelligence mining data from nine U.S. Internet companies in broad secret program", June 7 2013, http://www.washingtonpost.com/investigations/us-intelligence-mining-data-from-nine-us-internet-companies-in-broad-secret-program/2013/06/06/3a0c0da8-cebf-11e2-8845-d970ccb04497_story.html (Accessed June 20, 2013)
[#NSA slides explain]: NSA slides explain the PRISM data-collection program, Washington Post, June 6 2013, http://www.washingtonpost.com/wp-srv/special/politics/prism-collection-documents/ Accessed June 20, 2013)
[#Jihadism]: "Jihadism on the web, a breeding ground for jihad in the modern age", Netherlands General Intelligence and Security Service, Page 6, https://www.aivd.nl/english/publications-press/@2873/jihadism-web/ (Accessed 2 July 2013)
[#refused classification]: Collins, Stephen. "The truth about refused classification." The Drum Opinion. 14 October, 2010. http://www.abc.net.au/unleashed/40072.html (Accessed 30 March 2013).
[#notice 2821]: Question on notice no. 2821, Parliament of Australia, 11 February 2013, http://www.aph.gov.au/Parliamentary_Business/Chamber_documents/Senate_chamber_documents/qon/question?number=2821
[#ASIC spiderweb]: Wallbank, “ASIC's section 313 spiderweb”, 6 June 2013, http://www.businessspectator.com.au/article/2013/6/6/technology/asics-section-313-spiderweb (Accessed July 1 2013)
[#Secret blocking]: Wallbank, “The secret business of blocking websites”, 6 June 2013, http://www.smartcompany.com.au/business-tech-talk/055903-the-secret-business-of-blocking-websites.html (Accessed July 1 2013)