= Drugs

== Preamble

People have always taken drugs, and modern attempts at prohibition are at odds with history as well as human nature. The war on drugs is best understood as a war on a market. Such wars are futile: demand always creates supply, and ad-hoc attacks on supply channels do nothing other than reduce the quality of drugs, and increase the risks. History shows that even the harshest attempts to outlaw a market do not make the market go away, but merely create an unregulated black market in place of the legal one, making criminals of regular citizens and funding organised crime.

=== The cost of the war on drugs ===

At present the illegal drug market is worth around $300 billion per year,[#UN promoting health] making a mockery of prohibition. The choice we face is not between drugs and no drugs, but between legal and illegal markets.

The illegal market funnels vast profits to criminals and imposes equally vast costs on society. The US alone spends $50 billion per year fighting the war on drugs,[#What we don't know] and global spending is far greater. The secondary costs are incalculable: jailing people for drug offences does far more to destroy individual lives and potential than the drugs themselves. The policy is poorly targeted, excluding alcohol and tobacco but imposing massive punishments on non-violent users of much less harmful products.[#Drug danger] In producer countries, the illegal market has enriched drug cartels, causing thousands of deaths every year,[#Mexico drug war death] corrupting civil societies and creating a risk of failed states.

Prohibition offers no success to justify the cost: figures from the UN Office on Drugs and Crime show no observable decline in global drug use,[#UN drug market stats] nor is any decline evident in Australia.[p. 43][#Drugs in aus 2010] Results among individual nations show no correlation between drug use levels and the harshness of drug laws.[#How to stop drug wars]

=== The alternative ===

The experience of Portugal—where decriminalisation led to an observable fall in drug deaths[#Portugal effects]—suggests that a much better approach exists. Imprisonment is an immoral and ineffective way of handling mental health issues and other drivers of drug abuse. It is cheaper and more effective to handle these issues in the sphere of public health. Legalising and taxing safe drugs will raise revenue to fund better support services for addicts and their families. Decriminalising other drugs will broaden options for treatment and allow help to be extended without the threat of criminal sanctions. Effective policy must offer help and treatment, but must also recognise that most drug users are neither addicts nor criminals.

In handling drugs, policymakers should also take note of their one success: the campaign against tobacco. The anti-tobacco campaign has reduced the proportion of smokers by 40% over 20 years[p. 3][#Drugs in aus 2010] through a combination of advertising, warnings, and social sanctions in a legal framework. It is a far more successful model than prohibition, and a broader application of it should be considered.

Ultimately however, civil liberties must be respected. A belief in civil liberties does not require approval of every private choice, merely acceptance that choice should exist. The alternative has cost us too much, for too long.

The Pirate Party proposes that management of drugs be shifted into the public health arena through a combination of legalisation and decriminalisation.

== Policy Text

=== Legalise safe, non-addictive drugs ===

* A controlled substances committee will be established. The committee will meet periodically and will be tasked with several activities as specified below.
  * The committee members will be healthcare professionals assembled for this purpose and strive to make fact-based decisions.
* Psychoactive substance classification will be amended to conform to criteria such as:
  * Addictive properties
  * Habituating properties
  * Perception impairment
  * Reversible impact on the user
  * Known therapeutic properties
* Re-classification will be performed periodically by the controlled substances committee.
* Substances which are non-addictive and have a reversible impact on the user will be legalised, i.e. removed from any schedule that prohibits their use.
  * Marijuana[#Drug danger][#Is marijuana addictive][#Addictiveness of drugs][#Experts tell the truth about pot][#Problems posed by drugs][#Relative addictiveness][#Mechanistic classification] will be made available subject to appropriate health warnings and quality assurance.
* The committee will be able to recommend conditions for obtaining legalised substances, such as requiring a psychological evaluation, etc.
* Legalised drugs will be taxed.
  * Tax rates will be set at a level which balances the need to manage health impacts with the need to provide financial incentives to avoid the black market.
* Sales will be regulated.
  * Retailers will require licenses (as per conditions for selling alcohol)
  * Products will include mandatory warnings on health risks as recommended by manufacturers and relevant government bodies
  * Products will be restricted to sale in limited quantities, and may not be sold to intoxicated persons
  * All forms of advertising will be banned.
  * Products will be subject to strict quality control, with penalties for poor product quality being equivalent to those currently applied to pharmaceuticals.
  * Age verification will be required for all drug sales.
  * Exports will be controlled.
  * Exports to countries where drugs remain illegal will be a criminal offence unless products are sold under license to authorities in those countries that are legally permitted such purchases.
* Minors will be protected.
  * Making drugs available to minors will be a criminal offence.

=== Partially decriminalise drugs which fail to meet the threshold for legalisation ===

* Decriminalisation will apply to possession, purchase and consumption of small quantities of drugs for personal use.
  * Small quantities will be defined as a 14-day supply.
  * Infractions will be handled outside the criminal justice system, with preference given to the application of civil penalties including confiscation of drugs and treatment recommendations. Treatment may be imposed as part of a prosecution if other civil or criminal acts are committed by a person under the influence of drugs.
  * Users who work in professions with professional duty of care to others may face suspension of their right to practice under civil law.
  * Penalties for the sale of small quantities of decriminalised drugs will include fines and confiscation of products under civil law.
* Criminal sanctions will continue to apply for possession, sale or smuggling of substances in commercial quantities.
* Decriminalised drugs may be made available under prescription.
  * Supply would be procured following medical consultation in instances where harm minimisation or addiction treatment requires it, or as a mechanism for reducing black market purchasing.
  * Chemists providing drugs will be required to provide dosage levels, toxicity information, and information about side effects, as per standard requirements for medication.

=== Redirect existing resources and additional revenue to fund more research and support services ===

* Expand mental health services, rehabilitation facilities, and programs to assist addicts with social re-integration.
  * Persons seeking treatment will be entitled to protection of their privacy as per a doctor-patient relationship.
* Adopt harm minimisation techniques.
  * Pharmacies will be encouraged to make clean needles and drug testing kits available.
* Redirect police and prison resources towards preventing violent crime.
  * Curb the use of sniffer dogs and random "inspections" at public events.
* Undo restrictions on research and data collection imposed during prohibition.
  * Re-start research programs utilising previously banned drugs.
  * Re-start data collection on drug use and drug effects.

== References

[#UN promoting health]: United Nations Office on Drugs and Crime. "Promoting Health, Security and Justice - Cutting the Threads of Drugs, Crime and Terrorism 2010 Report." The UNOCD 2010 Report, p 44.
[#What we don't know]: National Research Council. Informing America’s Policy on Illegal Drugs: What We Don’t Know Keeps Hurting Us. Washington DC: The National Academic Press, 2001. p1.
[#Drug danger]: http://en.wikipedia.org/wiki/File:Drug_danger_and_dependence.svg
[#Mexico drug war death]: Mexico Gulf Reporter. "47,515 have died in Mexico's five year drug war, says country's Attorney General." Mexico Gulf Reporter. 11 January, 2012. http://www.mexicogulfreporter.com/2012/01/47515-have-died-in-mexicos-five-year.html (accessed 24 April, 2013).
[#UN drug market stats]: United Nations Office on Drugs and Crime. "Recent Statistics and Trend Analysis of Illicit Drug Markets." 2012. p 7. http://www.unodc.org/documents/data-and-analysis/WDR2012/WDR_2012_Chapter1.pdf (accessed 24 April, 2013).
[#Drugs in aus 2010]: Australian Institute of Health and Welfare. "Drugs in Australia 2010." November 2011. http://www.aihw.gov.au/WorkArea/DownloadAsset.aspx?id=10737420455 (accessed 24 April, 2013).
[#How to stop drug wars]: The Economist. "How to stop the drug wars." The Economist. 5 March, 2009. http://www.economist.com/node/13237193 (accessed 24 April, 2013).
[#Portugal effects]: Hughes, Caitlin & Stevens, Alex. The Effects of Decriminalization of Drug Use in Portugal. The Beckley Foundation Drug Policy Programme. December 2007. p5. http://www.beckleyfoundation.org/bib/doc/bf/2007_Caitlin_211672_1.pdf (accessed 24 April, 213).
[#Is marijuana addictive]: Gumbiner Ph.D., Jann. Is Marijuana Addictive? — Can recreational pot smokers become addicted?" Psychology Today. 5 December, 2010. http://www.psychologytoday.com/blog/the-teenage-mind/201012/is-marijuana-addictive (accessed March 2, 2013).
[#Addictiveness of drugs]: Hilts, Philip J. "Relative Addictiveness of Drugs." New York Times. 2 August, 1994. http://www.tfy.drugsense.org/tfy/addictvn.htm (accessed 2 March, 2012).
[#Experts tell the truth about pot]: Arkowitz, Hal & Lilienfeld, Scott O. "Experts Tell the Truth about Pot." Scientific American. 22 February, 2012). http://www.scientificamerican.com/article.cfm?id=the-truth-about-pot (accessed March 2, 2013).
[#Problems posed by drugs]: Roques Bernhard. Problemes posées par la dangerosité des drogues. Report to the Secretary of State for Health (France). 1998. Excerpts translated at http://www.chanvre-info.ch/info/en/Hemp-is-less-toxic-than-alcohol-or.html (accessed 2 March, 2013).
[#Relative addictiveness]: Hastings, John. "Relative Addictiveness of Various Substances." Schaffer Library of Drug Policy. November/December 1990. http://www.druglibrary.org/schaffer/misc/addictiv.htm (accessed March 2, 2013).
[#Mechanistic classification]: Lüscher, Christian & Ungless, Mark A. "The Mechanistic Classification of Addictive Drugs." PLOS Medicine. 14 November, 2006. http://www.plosmedicine.org/article/info:doi/10.1371/journal.pmed.0030437 (accessed March 2, 2013).