= Foreign Policy and Treaty Making

== Preamble

Civil and digital liberties, transparency, and human rights are universal principles and should be embodied in foreign as well as domestic policy. Indeed, foreign and domestic spheres are often difficult to separate, with international treaties having potential to drive domestic lawmaking.

Like all legal mechanisms, treaties derive legitimacy through consent and consultation. For this reason, treaties such as ACTA (which affect surveillance, [#ACTA] generic medicine,[#Blank cheque] and digital rights), have drawn concern due to the intense secrecy surrounding their formulation and negotiation. While the secrecy itself was nullified by regular leaks, the process was still seen to exclude many potentially affected parties. Far more legitimacy and balance will attach to treaty outputs when openness and participation are enshrined in the negotiation process, and potential threats to sovereignty are removed.

Recent revelations of massive and warrantless monitoring by the US National Security Agency also demand an alternative, and stronger response from the Australian government. Australians are being subjected to offshore monitoring on a massive scale with no checks and balances and no access to appeals or accountability. The notion that allies can be treated as suspects with no rights is harmful both to domestic sovereignty and broader international relations. One method of safeguarding the liberties of internet users will be to ensure that foreign whistle blowers offering information relevant to the public good are granted protection under Australian whistle blower laws. We also believe negotiations should commence on a new treaty to enshrine the principles of the internet and protect the rights of its users.

Australia should also continue to support human rights overseas, with the first step being to meet agreed aid targets. Plans to redirect foreign aid to handle domestic boat arrivals set a bad precedent and should be reversed. Properly targeted aid may well do more to reduce such arrivals in the long-run by curbing poverty and environmental damage overseas.

Foreign humanitarian aid should be provided for genuine humanitarian reasons, and in a manner that supports the improvement of local conditions. It is sometimes the case that aid is provided to foreign nations in situations where the real benefit is to the business and producers in the donor countries and the aid actually has negative effects upon the recipient countries.[#Hidden dumping][#Aid as dumping][#Wasted wealth] For example the increase in US rice delivered to Haiti as food aid in the wake of the disastrous earthquake of 2010 has out further pressure on local producers already struggling after years of their market being flooded by cheap, heavily subsidized US rice and very low tariffs imposed by the IMF. [#Food imports hurt][#Haitian farmers]

== Policy Text

=== Support principles of transparency and openness in treaties and trade agreements ===

* Ensure treaty negotiations are subject to oversight and public participation.
  * Require a window for public participation and the availability of draft texts prior to signing.
* Conduct a constitutional referendum to require parliamentary oversight and consent in treaty making and other international instruments.
* Renegotiate or withdraw from treaties which restrict policy making in areas of intellectual property reform and public health.
  * Treaties to be reviewed will include, but are not limited to:
    * Berne Convention
    * WIPO Copyright Treaty (WCT)
    * Anti-Counterfeiting Trade Agreement (ACTA)
    * Agreement on Trade Related Aspects of Intellectual Property Rights (TRIPS)
    * Australia-United States Free Trade Agreement (AUSFTA)
    * Single Convention on Narcotic Drugs
    * Convention on Psychotropic Substances
    * Convention Against Illicit Traffic in Narcotic Drugs and Psychotropic Substances
* Ensure Australia complies fully with all treaty clauses which protect individual rights.
  * Remove exceptions granted to Australia which potentially reduce the capacity of the International Covenant on Civil and Political Rights (ICCPR) to protect Australian citizens.[#Civil rights covenant]
* No inclusion of investor-state dispute settlement provisions in trade agreements.
  * Foreign businesses investing in Australia to retain equivalent legal protections to domestic businesses.
* Begin negotiations on an international treaty for a free and open internet.
  * Treaty should enshrine net neutrality, freedom from state control, and protection for private communication, free expression, and unrestricted access to information.

=== Expand use of diplomacy and aid in support of global human rights ===

* Increase foreign aid to 0.5 per cent of GDP by 2014-15 to meet the agreed deadline for Millennium Development Goals.[#AusAID][#Foreign spending]
  * Priorities for additional aid to include programs to support empowerment of women, environmental protection, regional capacity building (including renewable energy), emergency response, and provision of generic medicines (see patents policy).
  * Aid should be provided with consideration towards any deleterious effects upon the local economies of recipient countries, ensuring that local producers are not disadvantaged by the dumping of aid products, and with local suppliers of goods and services used where practical.
* Support political asylum or subsidiary protection status for overseas whistleblowers per provisions of Article 14 in the Universal Declaration of Human Rights. [#Universal HR]
* Suspend extradition processes and law enforcement cooperation in cases where:
  *   * Only political offences have been committed.
  * The act being investigated is not an offence in Australia.
  * A death penalty could potentially apply.
  * The nation involved has not ratified the United Nations Convention against Torture.
* Utilise diplomatic and political channels to seek urgent clarification from nations that Australia has intelligence sharing arrangements with regarding the scope of monitoring of Australian citizens by intelligence agencies.

== References

[#ACTA]: Article 27, Anti-Counterfeiting Trade Agreement, http://www.international.gc.ca/trade-agreements-accords-commerciaux/topics-domaines/ip-pi/acta-text-acrc.aspx?lang=eng#chapter2_sect5 (Accessed 8 July 2013)
[#Blank cheque]: A Blank Cheque for Abuse, Medecins Sans Frontieres, Pages 1-2, http://www.msfaccess.org/sites/default/files/MSF_assets/Access/Docs/Access_Briefing_ACTABlankCheque_ENG_2012.pdf (Accessed 8 July 2013)
[#Hidden dumping]: Food aid or hidden dumping, Oxfam Briefing Paper, 2005 http://www.oxfam.org/sites/www.oxfam.org/files/bp71_food_aid.pdf (Accessed 10 July 2013)
[#Aid as dumping]: Food Aid as Dumping, Anup Shah, 2005 http://www.globalissues.org/article/10/food-aid-as-dumping (Accessed 10 July 2013)
[#Wasted wealth]: J.W. Smith, The World’s Wasted Wealth 2, Institute for Economic Democracy, 1994, pp. 63, 64
[#Food imports hurt]: Food imports hurt struggling Haitian farmers, NBC News/Associated Press, 2010, http://www.nbcnews.com/id/35608836/ns/world_news-americas/t/food-imports-hurt-struggling-haitian-farmers/ (Accessed 10 July 2013)
[#Haitian farmers]: Haitian farmers undermined by food aid, Jacob Kushner, Centre for Public Integrity, 2012, http://www.publicintegrity.org/2012/01/11/7844/haitian-farmers-undermined-food-aid (Accessed 10 July 2013)
[#Civil rights covenant]: Department of Foreign Affairs and Trade, "International Covenant on Civil and Political Rights", http://www.austlii.edu.au/au/other/dfat/treaties/1980/23.html (Accessed July 9 2013)
[#AusAID]: Millennium Development Goals, AusAID, July 2013, http://www.ausaid.gov.au/aidissues/mdg/Pages/home.aspx (Accessed July 7 2013)
[#Foreign spending]: Lane, “Foreign spending boosted and aid money capped for onshore asylum costs”, 13 May 2013, http://www.abc.net.au/am/content/2013/s3757469.htm (Accessed July 7 2013)
[#Universal HR]: Article 14 - Universal Declaration of Human Rights, Archives of the International Council on Human Rights Policy, http://www.ichrp.org/en/article_14_udhr